# Setup
title: The Dig
tagline: The Dig
url: "arickert.github.io"
paginate: 1
baseurl: "/"
permalink: pretty



# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Mark Otto
  url: https://twitter.com/mdo
  email: markdotto@gmail.com

# Custom vars
version: 3.0.0

#pages
pages:       
  Options: '/2020/04/03/options/'
  Introduction: '/2020/04/04/introduction/'
  Archive: '/archive/'
  Categories: '/category/'
  Guests: '/tags/'



# Archives
collections:
  archives:
    output: true
    permalink: /archives/:path/
