name: Update Articles

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

env:
  DEVOPS_DIR: devops

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Run script to get articles from dev.to
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          -python -m pip install --upgrade pip
          pip install beautifulsoup4
      - name: run script
          python ../scripts/update-episodes.py
      - name: Commit to the repo
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email <>
          git add -all
          git commit -am "Update articles list"
          git push origin master


#or git add .?